[package]
name = "short-crypt"
version = "1.0.6"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rust-short-crypt"
homepage = "https://magiclen.org/short-crypt"
keywords = ["crypto", "qrcode", "url", "encrypt", "decrypt"]
categories = ["algorithms", "cryptography"]
description= "ShortCrypt is a very simple encryption library, which aims to encrypt any data into something random at first glance."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/rust-short-crypt", branch = "master" }
appveyor = { repository = "magiclen/rust-short-crypt", branch = "master", service = "github" }

[dependencies]
crc-any = "1.0.0"
base64-url = "1.1.7"
base32 = "0.4"